config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :news
  resources :podcasts  
  # resources :offers
  # resources :services
  # resources :users
  # resources :campuses

  get '/campus', to: 'campuses#location'
  get '/offer', to: 'offers#index'
  post '/users/sign_up', to: 'users#create'
  get '/users/sign_up', to: 'users#sign_up'
  post '/users/login', to: 'users#sign_in'
  get '/users/login', to: 'users#login'
  get '/users/logout', to: 'users#logout'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campus.rb
class Campus < ApplicationRecord
  self.table_name = :campuses
  has_many :events
  has_many :podcasts
  has_many :services

  def service_days
    services.collect(&:date)
  end

  def service_times
    services.collect(&:date).reject(&:blank?)
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :campus

  scope :upcoming, -> { where('date > ?', Time.now).order('date desc').limit(5) }
  # have a read on AR Scopes
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :campus

  default_scope { order(date: :desc).limit(5) }
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  belongs_to :campus

  default_scope { order(date: :desc).limit(5) }
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :campus
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  has_many :offers
end

app/controllers/campuses_controller.rb
class CampusesController < ApplicationController
  def location
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def new
    render_404 if !current_user.is_admin
  end

  def create
    event = Event.new
    event.image_url = params[:image_url]
    event.date = params[:date]
    event.title = params[:title]
    event.speaker = params[:speaker]
    event.campus_id = params[:campus_id]
    event.address = params[:address]
    event.save!
    redirect_to '/events'
  end

  def show
    @event = Event.find_by(id: params[:id]) || nil
  end

  def edit
    if !current_user.is_admin
      render_404
    else
      @event = Event.find_by(id: params[:id])
    end
  end

  def update
    event = Event.find_by(id: params[:id])
    event.image_url = params[:image_url]
    event.date = params[:date]
    event.title = params[:title]
    event.speaker = params[:speaker]
    event.campus_id = params[:campus_id]
    event.address = params[:address]
    event.save!
    redirect_to event
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to '/events'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def new
    render_404 if !current_user.is_admin
  end

  def create
    news = News.new
    news.image_url = params[:image_url]
    news.date = params[:date]
    news.title = params[:title]
    news.description = params[:description]
    news.campus_id = params[:campus_id]
    news.save!
    redirect_to '/news'
  end

  def index
  end

  def show
    @news = News.find_by(id: params[:id]) || nil
  end

  def edit
    if !current_user.is_admin
      render_404
    else
      @news = News.find_by(id: params[:id])
    end
  end

  def update
    news = News.find_by(id: params[:id])
    news.image_url = params[:image_url]
    news.date = params[:date]
    news.title = params[:title]
    news.description = params[:description]
    news.campus_id = params[:campus_id]
    news.save!
    redirect_to news
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to '/news'
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index
  end

  def new
    render_404  if !current_user.is_admin    
  end

  def create
    podcast = Podcast.new
    podcast.date = params[:date]
    podcast.title = params[:title]
    podcast.url = params[:url]
    podcast.campus_id = params[:campus_id]
    podcast.save!
    redirect_to '/podcasts'
  end

  def show 
    @podcast = Podcast.find_by(id: params[:id])
  end

  def edit
    if !current_user.is_admin
      render_404
    else
      @podcast = Podcast.find_by(id: params[:id])
    end
  end

  def update
    podcast = Podcast.find_by(id: params[:id])
    podcast.date = params[:date]
    podcast.title = params[:title]
    podcast.url = params[:url]
    podcast.campus_id = params[:campus_id]
    podcast.save!
    redirect_to podcast
  end

  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy
    redirect_to '/podcasts'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_up
  end

  def create
    user = User.new
    user.is_admin = false
    user.name = params[:name]
    user.email = params[:email]
    user.password = params[:password]
    user.save!

    redirect_to '/users/login'
  end

  def login
  end

  def sign_in
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      render :sign_up
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to '/users/login'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/views/events/_tile.html.erb
<div class="event-container">
  <h4 class="event-date"><%= event.date.strftime("%d/%m/%Y") %></h4>
  <%= link_to event do %>
    <%= image_tag(event.image_url, style: "display: block; margin: 0 auto; width: 230px; height: 200px;") %>
  <% end %>
  <h3 class="event-title"><%= event.title %></h3>
</div>

app/views/events/edit.html.erb
<%= form_tag @event, :method => :put, class: "text-center border border-light p-5" do %>

<h3 class="event-title">EDIT EVENT</h3>

<div class="template">
  <div class="form-group">
    <%= label_tag 'Image Url' %>
    <%= text_field_tag 'image_url', @event.image_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Date' %>
    <%= text_field_tag 'date', @event.date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @event.title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Speaker' %>
    <%= text_field_tag 'speaker', @event.speaker, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Campus id' %>
    <%= text_field_tag 'campus_id', @event.campus_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Address' %>
    <%= text_field_tag 'address', @event.address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= button_tag "Edit", class: "btn btn-primary btn-md", id: "button" %>
  </div>
</div>
<% end %>

app/views/events/index.html.erb
<h2 class="upcoming-title">Upcoming Event</h2>
<% Event.all.each do |event|%>
  <div class="upcoming-info">
    <div>
    <a href="/events/<%= event.id %>"><%= image_tag(event.image_url, style: 'display: block; width: 230px; height: 200px;') %></a>
    </div>
    <div class="upcoming-description">
      <p>Date: <%= event.date.strftime('%d-%m-%Y') %></p>
      <p>Time: <%= event.date.strftime('%l:%M') %>PM</p>
      <p>Speaker: <%= event.speaker %></p>
      <p>Location: <%= event.campus.address%></p>
    </div>
  </div>
<% end %>

<% if current_user && current_user.is_admin %>
  <div>
    <%= link_to new_event_url(@event), class: "btn btn-primary btn-md", id: "event-create" do %>
        Add
    <% end %> 
  </div>
<% end %>

app/views/events/new.html.erb
<%= form_tag "/events", class: "text-center border border-light p-5" do %>

<h3 class="event-title">CREATE EVENT</h3>

<div class="template">
  <div class="form-group">
    <%= label_tag 'Image Url' %>
    <%= text_field_tag 'image_url', nil, placeholder: "Type image url", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Date' %>
    <%= text_field_tag 'date', nil, placeholder: "2019-08-08 20:00", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', nil, placeholder: "Type title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Speaker' %>
    <%= text_field_tag 'speaker', nil, placeholder: "Type speaker", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Campus id' %>
    <%= text_field_tag 'campus_id', nil, placeholder: "Type campus id", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Address' %>
    <%= text_field_tag 'address', nil, placeholder: "Type address", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= button_tag "Create", class: "btn btn-primary btn-md", id: "button" %>
  </div>
</div>
<% end %>

app/views/events/show.html.erb
<div class="event-info">
  <h3 class="date"><%= @event.date.strftime('On %A, %e of %B %Y') %></h3>
  <h4 class="form-title"><%= @event.title %></h4>
  <%= image_tag(@event.image_url, style: "display: block; margin: 0 auto; width: 230px; height: 200px;") %>
  <p class="event-details">Speaker is <%= @event.speaker %></p>
  <p class="event-details"><%= @event.date.strftime('%I:%M%p') %> at <strong><%= @event.address %></strong></p>
</div>

<% if current_user && current_user.is_admin %>
  <div class="edit-delete-section"> 
    <%= link_to edit_event_url(@event), class: "btn btn-primary btn-md", id: "event-edit" do %>
       Edit
    <% end %> 
    <%= link_to @event, method: :delete, class: "btn btn-primary btn-md" do %>
      Delete
    <% end %>
  </div>
<% end %>

app/views/news/_tile.html.erb
<div class="event-container">
  <h4 class="event-date"><%= news.date.strftime("%d/%m/%Y") %></h4>
  <a href="/news/<%=news.id%>"><%= image_tag(news.image_url, style: "display: block; margin: 0 auto; width: 230px; height: 200px; border-radius: 50%;") %></a>
  <h6 class="news-title"><%= news.title %></h6>
</div>

app/views/news/edit.html.erb
<%= form_tag @news, :method => :put, class: "text-center border border-light p-5" do %>

<h3 class="bridge-news-title">EDIT NEWS</h3>

<div class="template">
  <div class="form-group">
    <%= label_tag 'Image Url' %>
    <%= text_field_tag 'image_url', @news.image_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Date' %>
    <%= text_field_tag 'date', @news.date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @news.title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Description' %>
    <%= text_field_tag 'description', @news.description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Campus id' %>
    <%= text_field_tag 'campus_id', @news.campus_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= button_tag "Edit", class: "btn btn-primary btn-md", id: "button" %>
  </div>
</div>
<% end %>

app/views/news/index.html.erb
<h2 class="bridge-news-title">Bridge Church News</h2>
  <% News.all.each do |news| %>
    <div class="news-info">
      <div>
        <a href="/news/<%= news.id %>"><%= image_tag(news.image_url, style: 'display: block; width: 230px; height: 200px; border-radius: 50%;') %></a>
      </div>
      <div class="news-description">
        <p>Date: <%= news.date.strftime('%d-%m-%Y') %></p>
        <p>Title: <%= news.title %></p>
        <p>Description: <%= news.description %></p>
        <p>Location: <%= news.campus.address %></p>
      </div>
    </div>
  <% end %>

<% if current_user && current_user.is_admin %>
  <div>
    <%= link_to new_news_url(@news), class: "btn btn-primary btn-md", id: "event-create" do %>
        Add
    <% end %> 
  </div>
<% end %>

app/views/news/new.html.erb
<%= form_tag '/news', class: "text-center border border-light p-5" do %>

  <h3 class="bridge-news-title">CREATE NEWS</h3>

  <div class="template">
  <div class="form-group">
    <%= label_tag 'Image Url' %>
    <%= text_field_tag 'image_url', nil, placeholder: "Type image url", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Date' %>
    <%= text_field_tag 'date', nil, placeholder: "2019-08-08 20:00", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', nil, placeholder: "Type title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Description' %>
    <%= text_field_tag 'description', nil, placeholder: "Type description", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Campus id' %>
    <%= text_field_tag 'campus_id', nil, placeholder: "Type campus id", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= button_tag "Create", class: "btn btn-primary btn-md", id: "button" %>
  </div>
</div>
<% end %>

app/views/news/show.html.erb
<div class="event-info">
  <h3 class="date"><%= @news.date.strftime("%d/%m/%Y") %></h3>
  <h4 class="form-title"><%= @news.title %></h4>
  <%= image_tag(@news.image_url, style: "display: block; margin: 0 auto; width: 230px; height: 200px;") %>
  <p class="event-details"><%= @news.description %></p>
</div>

<% if current_user && current_user.is_admin %>
  <div class="edit-delete-section"> 
    <%= link_to edit_news_url(@news), class: "btn btn-primary btn-md", id: "event-edit" do %>
       Edit
    <% end %> 
    <%= link_to @news, method: :delete, class: "btn btn-primary btn-md" do %>
      Delete
    <% end %>
  </div>
<% end %>

app/views/offers/index.html.erb
<form>
  <label for="">Giving:</label>
  <input type="text" />
  <button class="btn btn-info btn-sm">Pay</button>
</form>

app/views/podcasts/_tile.html.erb
<div class="event-container">
  <h4 class="podcast-date"><%= podcast.date.strftime("%d/%m/%Y") %></h4>
  <h6><%= link_to "#{podcast.title}", podcast ,class: "podcast-url" %></h6>
</div>

app/views/podcasts/edit.html.erb
<%= form_tag @podcast, :method => :put, class: "text-center border border-light p-5" do %>

<h3 id="podcast-title">EDIT PODCAST</h3>

<div class="template">
  <div class="form-group">
    <%= label_tag 'Date' %>
    <%= text_field_tag 'date', @podcast.date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', @podcast.title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Url' %>
    <%= text_field_tag 'url', @podcast.url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Campus id' %>
    <%= text_field_tag 'campus_id', @podcast.campus_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= button_tag "Edit", class: "btn btn-primary btn-md", id: "button" %>
  </div>
</div>
<% end %>

app/views/podcasts/index.html.erb
<h2 id="podcast-title">Bridge Church Podcasts</h2>
<% Podcast.all.each do |podcast|%>
  <div class="podcast-container">
    <h6><%= podcast.date.strftime('%d-%m-%Y') %></h6>
    <%= link_to "#{podcast.title}", "#{podcast.url}", class: "podcast-link"%>
    <h6><%= podcast.campus.address %></h6>
  </div>
<% end %>

<% if current_user && current_user.is_admin %>
  <div>
    <%= link_to new_podcast_url(@podcast), class: "btn btn-primary btn-md", id: "event-create" do %>
        Add
    <% end %> 
  </div>
<% end %>

app/views/podcasts/new.html.erb
<%= form_tag '/podcasts', class: "text-center border border-light p-5" do %>

<h3 id="podcast-title">CREATE PODCAST</h3>

<div class="template">
  <div class="form-group">
    <%= label_tag 'Date' %>
    <%= text_field_tag 'date', nil, placeholder: "2019-08-08 20:00", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= text_field_tag 'title', nil, placeholder: "Type title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Url' %>
    <%= text_field_tag 'url', nil, placeholder: "Type URL", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Campus id' %>
    <%= text_field_tag 'campus_id', nil, placeholder: "Type campus id", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= button_tag "Create", class: "btn btn-primary btn-md", id: "button" %>
  </div>
</div>
<% end %>

app/views/podcasts/show.html.erb
<div class="podcast-info">
  <h6><%= @podcast.date.strftime("%d/%m/%Y") %></h3>
  <%= link_to "#{@podcast.title}", "#{@podcast.url}", class: "podcast-link"%>
  <h6><%= @podcast.campus.address %></h6>
</div>

<% if current_user && current_user.is_admin %>
  <div class="edit-delete-section"> 
    <%= link_to edit_podcast_url(@podcast), class: "btn btn-primary btn-md", id: "event-edit" do %>
       Edit
    <% end %> 
    <%= link_to @podcast, method: :delete, class: "btn btn-primary btn-md" do %>
      Delete
    <% end %>
  </div>
<% end %>

app/views/users/login.html.erb
<%= form_tag '/users/login', class: "text-center border border-light p-5" do %>

  <p class="sign-in">SIGN IN</p>

  <div class="loginform">
    <div class="form-group">
      <%= label_tag 'Email' %>
      <%= text_field_tag 'email', nil, placeholder: 'Email', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Password' %>
      <%= password_field_tag 'password', nil, placeholder: 'password', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= button_tag 'Login', class: "btn btn-info btn-block my-4 waves-effect waves-light" %>
    </div>
  </div>

  <p class="small text-center text-gray-soft">Don't have an account yet? <a href="/users/sign_up">Sign up</a></p>

<% end %>

app/views/users/sign_up.html.erb
<%= form_tag "/users/sign_up", class: "text-center border border-light p-5" do %>

  <p class="sign-up">SIGN UP</p>

  <div class="signupform">
    <div class="form-group">
      <%= label_tag 'Name' %>
      <%= text_field_tag 'name', nil, placeholder: 'Name', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Email' %>
      <%= text_field_tag 'email', nil, placeholder: 'Email', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Password' %>
      <%= password_field_tag 'password', nil, placeholder: 'password', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= button_tag 'Sign Up', class: "btn btn-info btn-block my-4 waves-effect waves-light" %>
    </div>
  </div>

  <p class="small text-center text-gray-soft">Already have an account? <a href="/users/login">Login</a></p>
<% end %>